//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication5.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class billSalesDetail
    {
        public int id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public int BillSalesId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string Totalprice { get; set; }
    
        public virtual billSale billSale { get; set; }
    }
}
