//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication5.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class billSale
    {
        public billSale()
        {
            this.billSalesDetails = new HashSet<billSalesDetail>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CustormerId { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<billSalesDetail> billSalesDetails { get; set; }
    }
}
