//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication5.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppler
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string address { get; set; }
        public string Notes { get; set; }
        public string phone { get; set; }
        public string company { get; set; }
        public string email { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string Image { get; set; }
    }
}
